pixiv/charcoal

docs/pages/utilities/styled.md
package.json

- @charcoal-ui/styled のドキュメント内の画像URLのパスが間違っていたものを修正
- viteで起動するwebsiteのサーバーのbase pathを更新

@charcoal-ui/styled のドキュメントを修正

---

package.json

[test workflowのPrepare deps](https://github.com/pixiv/charcoal/blob/1396b1fda5e4a1201acd5e4da542035a5b211b6b/.github/workflows/test.yml#L41-L44) だけで4分半くらいかかっていたので最高1分くらい速くしました
[`yarn build` 内で利用している `yarn workspaces foreach`](https://github.com/pixiv/charcoal/blob/1396b1fda5e4a1201acd5e4da542035a5b211b6b/package.json#L13) ですが、
https://yarnpkg.com/cli/workspaces/foreach によると
> If -p,--parallel is set, the commands will be ran in parallel; they'll by default be limited to a number of parallel tasks roughly equal to half your core number
とあります。
しかし [GitHub ActionsのHosted Runnerの `ubuntu-latest`](https://docs.github.com/ja/actions/using-github-hosted-runners/about-github-hosted-runners) は2-core CPUなので、GitHub Actions上だと `yarn workspaces foreach -vpt run build` …

Prepare depsを1分くらい速くした

---

.eslintrc.js
jest.config.mjs
jest.setup.js
jest.setup.ts
package.json
packages/react/src/components/Radio/index.story.tsx
packages/react/src/components/Radio/index.test.tsx
packages/react/src/components/Radio/index.tsx
packages/react/src/components/TextField/index.story.tsx
packages/react/src/components/TextField/index.tsx
packages/react/src/components/a11y.test.tsx
tsconfig.json
yarn.lock

- TextFieldにprefix,suffix文字列を付与できるように機能追加
- RadioGroupの状態管理を内部で行わないように変更

Support prefix,suffix on TextField component. Change RadioGroup state management.

---

packages/icons-cli/src/index.ts

`npx @charcoal-ui/icons-cli` などとしたときにnodeと認識されずにエラーが出てしまう問題を解決したい
```
/Users/xxx/node_modules/.bin/icons-cli: line 1: syntax error near unexpected token `('
/Users/xxx/node_modules/.bin/icons-cli: line 1: `var fsExtra = require('fs-extra');'
```
- icons-cliにshebangを追加
- distに生成されるindex.cjsとindex.modern.jsにshebangがついているのを確認

icons-cliにshebangを追加

---

packages/react/src/components/TextField/index.tsx

- Production buildでbabelのloose modeが使われていることが原因で、TextFieldの文字数カウントが常に1になってしまうのを修正した。
- TextFieldのvalue propを変更したときに文字数カウントが更新されないのを修正した。

TextFieldの文字数カウントが壊れているのを修正

---

lerna.json
package.json

- `conventional-changelog-conventionalcommits` を `changelogPreset` に指定
- デフォルトでは [Angular Commit Message Conventions](https://github.com/conventional-changelog/conventional-changelog/blob/21b73f974adc4490a318d9c892055655cb82c538/packages/conventional-changelog-angular/parser-opts.js) が使われていて、`feat!:` のような!の指定でBREAKING CHANGE判定になっていなかった
- `changelogPreset` は changelog の生成とバージョン推論の両方に使われる
- `--no-changelog` のcli引数で changelog の生成は抑制しつつ、バージョン推論に conventionalcommits が使われるようにした

Use conventional-changelog-conventionalcommits preset for version bumping

---

docs/pages/components/icons.md

- iconsはdevのパッケージではなくdependenciesに入っていてほしいので `--save-dev` と `-D` のオプションをdocsから削除しました
- docsだけなので特にありません

docs: iconsはdevパッケージではないためdevオプションを削除した

---

packages/tailwind-config/src/util.ts

- `mapKeys`/`mapObject`/`flatMapObject`/`filterObject` に JSDoc の `@example` を追加した
各所でかなり使われている割に型からは挙動が把握しづらいものもあるので
Deno でサンプルをそのまま実行して評価結果が正しいことを確認しました

docs: add JSDoc @example for `mapKeys`/`mapObject`/`flatMapObject`/`filterObject`

---

packages/tailwind-config/src/docs/borderRadius/BorderRadius.tsx
packages/tailwind-config/src/docs/borderRadius/index.story.mdx
packages/tailwind-config/src/docs/borderRadius/index.ts
packages/tailwind-config/src/docs/screens/Screens.tsx
packages/tailwind-config/src/docs/screens/index.story.mdx
packages/tailwind-config/src/docs/screens/index.ts
packages/tailwind-config/src/docs/spacing/Spacing.tsx
packages/tailwind-config/src/docs/spacing/index.story.mdx
packages/tailwind-config/src/docs/spacing/index.ts

Tailwind config の `spacing` / `borderRadius` / `screens` などのドキュメントを実装した
Storybook

docs: add docs for some of the customized Tailwind config

---

jest.config.mjs
packages/icons/package.json
packages/icons/src/PixivIcon.ts
packages/icons/src/index.ts
packages/icons/src/ssr.ts
yarn.lock

関連 #45 
- icons は Custom Elements として実装されており、現状 lit-html を使っている
- React の SSR で icons を使いたい需要に答えようと思うと lit-html が問題になる
- lit-html はバリバリ DOM API を使っており、node.js 環境では import しただけでエラーになる
- lit-labs/ssr というものがあるが、実体は DOM API の polyfill（グローバル変数）を node.js に定義しまくるというもので、あまり Universal に設計する気がなさそう
- https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/dom-shim.ts
というわけで lit-html をやめる。
単純に innerHTML をいじる実装にしつつ、安全のため DOMPurify を使うようにする。PixivIcon のクラスはサーバーサイドでインスタンス化さえしなければ OK という設計にする。
innerHTML 全置換えにした結果レンダリングパフォーマンスが悪化しないかが気になる
Storybook

icons: SSR 対応を簡単にするため lit-html の利用をやめる

---

packages/styled/src/index.ts

- themeがnullableな場合に親切なエラーメッセージを出す

styled: ThemeProviderが入っていない場合にエラーにする

---

packages/icons/src/PixivIcon.ts
packages/react/package.json
packages/react/src/components/Icon/index.story.tsx
packages/react/src/components/Icon/index.tsx

`@charcoal-ui/react` の `<Icon>` に何故か `{ css: unknown }` という必須の props が生えてしまう問題がある。
原因は、`IconProps` に `css` が含まれてしまっている（ おそらく根っこには `React.DetailedHTMLProps` に `css` が含まれてしまっている ）こと。
これを除いた型定義にしたい。
`@charcoal-ui/react` でだけ Omit するのが良いか、それとも `@charcoal-ui/icons` の方も除いてしまうほうが良いか。
今の所 `@charcoal-ui/react` でしかこの問題は発見されてないが、`@charcoal-ui/icons` を直で `styled-components` と合わせた時に同じ問題が起きうるか？
実は Next.js 環境でしか再現したのを見たことないのでなんか適当にプロジェクトを作る必要がありそう…

chore(react): omit css props from IconProps

---

packages/react-sandbox/src/components/TextEllipsis/index.tsx
stylelint.config.js

- TextEllipsis の `display: box` を `display: -webkit-box` に
- stylelint の autofix によって書き換えられてしまっていたので、該当のルールで `-webkit-box` は無視するように
- https://stylelint.io/user-guide/rules/list/value-no-vendor-prefix/
手元で storybook を立ち上げて確認しました

fix(react-sandbox): TextEllipsis コンポーネントで 2行以上の場合に ellipsis が表示されていなかった

---

docs/pages/components/icons.md
packages/icons/README.md

ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_single_export_from_a_module

docs(icons): resolving import error in example

---

packages/icons/src/PixivIcon.ts
packages/icons/src/ssr.ts

- `extends HTMLElement` の形状を保つように修正
- 継承元に式があるパターンでbabelのトランスパイル結果が変わる
- 本質的にはCustom Elementsはes6 classを用いる仕様になっている。しかしes6ターゲットにビルド環境を変更するのが困難であるため、いったん回避策を取ることにした。
index.module.js で以下のエラーが出ていた。これはes5化されたクラスにおいて、ネイティブクラスであるHTMLElementをnew以外の方法でインスタンス化しようとした際にエラーになっている。
```
Unhandled Runtime Error
TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```
index.modern.js ではモダンビルドでes6 classが維持されているため、エラーにならない。

icons の custom elements が esm bundle (es5) で動作しない問題を修正

---

packages/icons/src/PixivIcon.ts

https://github.com/pixiv/charcoal/pull/57
- icons の中身が一度読み込み済になったあとで name を変更した場合に、中身が変更されてなさそう
そろそろ pixiv-icon のテストを復活させたい…

fix(icons): たとえ this.svgContent があったとしても name が変わったら必ず load

---

packages/icons/src/PixivIcon.ts

https://github.com/pixiv/charcoal/pull/64
- loadSvg にはつねに name の内容を渡すべきだが、 name 以外の属性が変わった場合は当該属性の値が渡っている

fix(icons): newValue is not a name when attr !== 'name'

---

packages/icons/src/PixivIcon.ts

- 同一のsvgをロードするpromiseが既に存在する場合に描画が走らない問題を修正

icons: 同一のnameのsvgがロード中の場合にアイコンが描画されないケースの修正

---

packages/react-sandbox/src/components/Carousel/index.tsx

- カルーセルのスクロール幅の算出基準を画面幅からカルーセルのコンポーネント幅に変更しました。
- スクロール量の割合をpropsで渡せるようにしました。(指定しなかった場合は従来通りの0.75です)
手元で`yarn storybook`を行い確認しました

chore(react-sandbox): カルーセルのスクロール修正

---

packages/react-sandbox/src/components/Carousel/index.tsx
packages/react-sandbox/src/foundation/support.ts

文脈: Next.js環境化で`@charcoal-ui/recat-sandbox`を使おうとすると`isEdge`を評価しようとして`ReferenceError: navigator is not defined`というエラーが出ていた。
- `isEdge`を関数にして評価を遅延させるように
- CarouselコンポーネントをSSRできるように`useLayoutEffect`の中で`isEdge`を使用
- ただし`useLayoutEffect`を使うことのwarningは出る
- 追記: どうやら[これだけではSSRはできない](https://github.com/pixiv/charcoal/pull/71#issuecomment-1156263806)のでSSRする場合さらなる修正が必要
- `yarn build`が通る (WSL2)
- ビルドしたものを該当Next.jsプロジェクトに持っていってエラーが消えることを確認
質問: この変更は破壊的変更に含まれますでしょうか？

fix(react-sandbox): Next.js環境化で使えるようにisEdgeを関数に

---

packages/theme/src/default.ts

- surface9のlightテーマの色が間違っていたので修正

chore: fix surface9(light) color

---

packages/sample/package.json
packages/styled/src/helper.ts
yarn.lock

- `document.createEvent` → `new StorageEvent()`
snapshotテスト時に`document.createEvent`では以下のエラーがでる
`NotSupportedError: The provided event type ("StorageEvent") is invalid`
こういうmockすると
```
const original = document.createEvent
Object.defineProperty(document, 'createEvent', {
writable: true,
value: jest.fn().mockImplementation(x => x === 'StorageEvent' ? {} : original(x))
```
Reactの`Error: Should not already be working`が出てエラーになる
https://github.com/facebook/react/issues/17355

fix(styled): use StorageEvent constructor

---

packages/sample/pages/_app.tsx
packages/sample/pages/_document.tsx
packages/styled/src/SetThemeScript.tsx
packages/styled/src/helper.ts
packages/styled/src/index.ts

- テーマの初期化方法を変更
- Next.jsではscriptがdeferなため、DOMContentLoadedより前に描画が実行されることがある。そのためにテーマの初期変更が描画より後に行われてしまう問題を修正。
なし

feat(styled): changed theme initialization

---

docs/pages/utilities/styled.md

- docsが`TokenInjector`を利用する形になっていなかったので、修正

TokenInjectorによる変更をdocsに反映

---

packages/react/src/components/TextField/index.story.tsx
packages/react/src/components/TextField/index.tsx

- 文字数カウント分、テキストインプットの高さを大きくして、テキスト入力エリアと文字数カウントがかぶさらないように修正
https://user-images.githubusercontent.com/1888491/179649608-b58f242e-ded5-4afb-a096-583a18155a48.mov

複数行テキストインプットの文字数カウントがテキストとかぶるデザインを修正

---

docs/pages/components/react.md

- `@charcoal-ui/react` を利用しているプロジェクトがスナップショットテストを行っている場合、react-aria の挙動でハマる可能性があるのでドキュメントに追記する

chore: update react docs (notes on snapshot test)

---

packages/react/src/components/TextField/index.tsx

- TextFieldコンポーネントにて、showCount==trueの場合に文字数を表示するようにし、maxLengthも指定された場合は最大文字数も表示するように修正しました。
node v16.5.0
Macbook Air M1 (macOS 12.3 Monterey)

TextFieldのMultiLineでMaxLengthを表示するように修正

---

packages/react/src/components/TextField/index.tsx

- multilineなTextFieldがコンテナをはみ出し、スクロールバーが表示されているのを修正した。
- transformで大きさを変えているので、見た目ではコンテナに収まっているのにスクロールバーが表示されてしまっていた。
|Before|After|
|-|-|
|<img width="597" alt="image" src="https://user-images.githubusercontent.com/15273128/182751257-39e1fb18-69c2-4679-8472-64853ce1fb27.png">|<img width="597" alt="image(1)" src="https://user-images.githubusercontent.com/15273128/182751289-691e640a-66c1-491a-8fe8-9735be01bb25.png">|

TextFieldがコンテナからはみ出しているのを修正

---

.github/workflows/test.yml
.storybook/main.js
package.json
packages/icons/src/PixivIcon.ts
yarn.lock

- #109 の確認を `yarn storybook:experimental-vite` でやろうと思ったら動いてない箇所があった
- https://github.com/storybookjs/builder-vite#migration-from-storybook-builder-vite にしたがって最新にしつつエラーを潰す
これ CI で見るようにしたほうが良いかも
手元で `yarn storybook:experimental-vite`

Storybook の Vite モードが動いてなさそうだったので修正 + アップデート

---

packages/react/src/components/TextField/index.tsx

fixes: #103
TextField(multiline)でerrorよりfocusのoutlineが優先されてしまうのを直す
手元で `yarn storybook`

fix: TextField(multiline)が invalid なら outline は赤くあって欲しい

---

packages/react-sandbox/src/components/Carousel/index.tsx

ref: #71
- ResizeObserver はブラウザ API であり、レンダリングの最中に new すると SSR のときエラーの原因になる
- 素直に useLayoutEffect の中で new したほうが良い

ResizeObserver をレンダリングの最中に初期化しない（ SSR のとき困るので ）

---

packages/icons-cli/src/getChangedFiles.ts

- icons-cliが`packages/icons/svg/‘配下が展開されず、PRにファイルの変更が含まれなかった問題を修正しました。
- ディレクトリの中のファイルを取る処理が1段分しかなく、`svg/16/hoge.svg`のようなファイルの差分を検出できていなかった
- gitによって変更が検出されたファイルの中でパスの前方が指定ディレクトリと一致するファイルのみをリストする処理に変更しました
手元で確認するか、試しにCIを実行する
https://github.com/pixiv/charcoal/pull/107

icons-cliの修正

---

packages/theme/src/default.ts

ダークテーマのリンクの色を修正

---

.storybook/preview.js
packages/react/src/components/TextField/index.story.tsx
packages/react/src/components/TextField/index.tsx
packages/react/src/index.ts

- `TextField`に`onKeyDown`, `onFocus`, `onBlur`を実装した
- `SingleLineTextFieldProps`と`MultiLineTextFieldProps`をexportするようにした
- `TextField`のstoryにおいて、一部のactionでレガシーな記法([Manually-specified actions](https://github.com/storybookjs/storybook/blob/master/addons/actions/ADVANCED.md#manually-specified-actions))が使われていたので新しい記法([Automatically matching args](https://storybook.js.org/docs/react/essentials/actions#automatically-matching-args))に可能な限り統一した

TextFieldでlistenできるイベントを追加

---

packages/foundation/package.json
packages/icons-cli/package.json
packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/theme/package.json
packages/utils/package.json

- ビルド時にminificationしないようにした
- minifyすると、charcoalを使用するアプリケーションを開発する際にデバッグが難しくなるため
- minifyはcharcoalを使用するアプリケーションが行うべきであるため

Minificationをやめる

---

.github/workflows/test.yml

- ときどき GitHub Actions の test ジョブが落ちる
- storybook の vite build が OOM で落ちるせいっぽいので何とかする
- max_old_space_size を引き上げるみたいな方法と runs_on を変えるみたいな方法がそれぞれ思いつくがどうするか（考え中）
CI

storybook の vite build が OOM で落ちることがあるので何とかする

---

packages/react/README.md
packages/react/package.json
packages/react/src/core/SSRProvider.tsx
packages/react/src/index.ts
yarn.lock

- `<SSRProvider>`コンポーネントを追加した
- react-ariaを使用するとき、SSRを行う場合はアプリケーション全体を`<SSRProvider>`で囲む必要がある
- 現在はcharcoalを使用するアプリケーションがreact-ariaから`SSRProvider`をimportしなければいけない
- これは変なので、charcoalから`<SSRProvider>`を再exportするようにした

<SSRProvider>を追加

---

packages/icons-cli/package.json
packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/sample/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/theme/package.json
yarn.lock

下記バージョンの更新がコミットされていなかったため手動で更新
```
- @charcoal-ui/icons-cli@1.0.1-alpha.5
- @charcoal-ui/icons@1.1.0-alpha.6
- @charcoal-ui/react-sandbox@2.0.0-alpha.9
- @charcoal-ui/react@2.0.0-alpha.20
- @charcoal-ui/styled@2.0.0-alpha.3
- @charcoal-ui/tailwind-config@1.0.1-alpha.5
- @charcoal-ui/theme@2.0.0-alpha.5
```

手動のバージョン更新

---

packages/react/src/components/TextField/index.tsx

-  autoHeight を有効にした TextField でテキストをまとめて消すと rows が initialRows に戻らないバグを修正
Storybook で動画のバグが修正されていることを確認してください。
https://user-images.githubusercontent.com/38908416/182281727-a1560e4f-1ebc-40c3-a6d1-b46d70d335f1.mov

TextField の autoHeight で rows が initialRows に戻らないバグを修正

---

packages/tailwind-config/package.json
yarn.lock

- tailwindcss のバージョン指定を `~1.4.6` から `>=1.4.6` に修正

tailwind-config が npm v7 以降で peer deps エラーが発生しインストールできないバグを修正

---

.github/workflows/icons.yml

- icons-cliのCIで `svg:optimize` を走らせていなかったので、走らせるように修正した
GitHub Actionsの `icons` を見てください

fix(icons-cli): svg optimize

---

.github/workflows/gh-pages.yml
.github/workflows/icons.yml
.github/workflows/test.yml
.github/workflows/version.yml

https://github.com/pixiv/charcoal/actions/runs/3288171439 に下記のようなdeprecation warningが出ていたので直しました
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/cache, actions/cache, actions/setup-node, actions/checkout
これは今までの経験上メジャーバージョンを上げればだいたいなおったのでとりあえず全部最新にしてます
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[GitHub Actions の set\-output を sed で $GITHUB\_OUTPUT 形式に置換 \- …

Resolved deprecation warning in GitHub Actions

---

packages/sample/package.json
packages/sample/pages/_document.tsx
packages/styled/src/SetThemeScript.tsx
yarn.lock

- `SetThemeScript`のsrcを文字列として取得できる関数を追加
- 12.1.6だとbeforeInteractiveでinlineが使えなかったのでsampleのnextのバージョンを上げた

feat: add makeSetThemeScriptCode

---

misc/icons-cli-denylist
packages/icons-cli/src/svg/optimizeSvg.ts
packages/icons-cli/src/svg/optimizeSvgInDirectory.ts

- svgの最適化による圧縮を行わずに色を置換できるように変更
- misc/icons-cli-denylistから不必要なアイコンを削除
- Gift.svgのようなアイコンはsvgoによるコンバートで見た目が変わってしまうが、fillの置換だけは行いたいため。
- PremiumMulticolor.svgなどは存在していない。
- Play.svgなどはfillの限定的な置換に対応していなかった時の回避策でリストに追加されていたが、特定の色のみcurrentColorへ置換するようにしたので削除して問題ない。

svgの最適化による圧縮を行わずに色を置換できるように変更

---

packages/icons-cli/src/figma/FigmaFileClient.ts

- FigmaのURLをパースする処理を、`fileId`と`nodeId`で別々に行うのではなく同時に行うようにした
icons-cliを実行してdiffが出ないことを確認した

refactor(icons-cli): refactor figma URL parsing

---

packages/icons-cli/src/figma/FigmaFileClient.ts

- アイコン名（`Inline/Add`, `16/Check`など）にマッチする正規表現を調整した
- `(\d|Inline)+`を `(\d+|Inline)`に変更
- non-capturing groupに変更
- 末尾の`\s*`は無意味なので削除
`icons-cli`を実行してdiffが出ないことを確認した

refactor(icons-cli): optimize regexp for icon name

---

packages/icons-cli/src/index.ts

- `yargs`に渡す引数の形式をシンプルにした
- `yargs`に渡すコマンドハンドラをasync functionにして、エラーハンドリングをyargsに任せることにした
- `yarn icons-cli figma:export`, `yarn icons-cli svg:optimize`, `yarn icons-cli source:generate`が正常に実行できることを確認した
- 誤った`FIGMA_TOKEN`を渡したとき、エラーが表示されることを確認した

icons-cli: コマンドライン引数の処理をリファクタ

---

packages/react/src/components/Modal/index.story.tsx
packages/react/src/components/Modal/index.tsx
packages/react/src/index.ts

#90 の際、index.ts からの再 export を忘れていたと思われる
これ系 CI で根本対応したい…

fix: charcoal-ui/react から Modal が export されていない

---

README.md

npmパッケージのバッジを追加．パッケージが多いためテーブルにした．
各パッケージのnpmへのリンクがREADME.mdにないため．

docs: add npm badges

---

packages/tailwind-config/src/__snapshots__/index.test.ts.snap
packages/tailwind-config/src/index.ts

- tailwind/widthのclassNameに`w-fit`を追加
- `w-fit(width: fit-content)`をclassNameから指定できないため
- Macbook Pro Intel系/google chrome
- storybook内で確認。
以下3つのチェックリストに対して影響はないと思われる。

fix: add w-fit to width class name

---

.prettierignore

lerna.json を .prettierignore に加える。
`yarn lerna version` コマンドを打ったときに自動で lerna.json が変更されるが、その内容が prettier に怒られることがあるため。

chore: prettierignore lerna.json

---

packages/icon-files/src/index.cjs
packages/icons-cli/src/generateSource.ts

`2.0.0-rc.0` を Next.js で使用したらこのようになった
理由は cjs なのに `export default` をしているせい。
最初各アイコンファイル（ `16/Add.js` ）とかも含めて全部 `module.exports = ` にしないとダメかと思ったが、手元で node_modules をいじりながら試した感じ `index.cjs` を直すだけで行けそうな感じだったのでそうしてみた

icon-files/index.cjs は module.exports = してて欲しい

---

.github/workflows/icons.yml
packages/icons-cli/src/GitHubClient.ts
packages/icons-cli/src/GitlabClient.ts
packages/icons-cli/src/getChangedFiles.ts
packages/icons-cli/src/index.ts

- `OUTPUT_ROOT_DIR` をみて差分をとるディレクトリを決めるように変更
- `OUTPUT_ROOT_DIR` が与えられなかったときは処理をそこでやめる
手元で動かして動作確認をしました

[icons-cli] Pull Request作成サブコマンドでOUTPUT_ROOT_DIRを使う

---

packages/react/package.json
packages/react/src/index.ts
yarn.lock

thx @motoki317 
1.  (エラー報告) ModalのpropにisOpenを渡そうとすると、そんなpropは:naiyo: と怒られました。どうやらcharcoalを使う側で `@react-aria/overlays` の最新バージョン3.12.0がインストールされてしまうのが原因らしく、package.jsonのresolutionsで、charcoalで使っている3.9.1を指定してあげるとエラーが消えました。こちらは `@react-aria/overlays` の破壊的変更が原因でしょうか...？
2. ModalPlumbingからexportされているModalAlign等の要素を使いたかったのですが、exportされていないようです。こちらは意図的ですか？
1 については実際 react-aria で useOverlay の代わりに useModalOverlay の利用が推奨されるようになった？とかで OverlayProps の想定される使い方が変わってしまってそう（ see: https://github.com/adobe/react-spectrum/pull/3561 https://github.com/adobe/react-spectrum/pull/3347 ）
2 についてはそのとおりなので、Modal.tsx 以外からも export する
Storybook

fix: rc.1 の `<Modal>` コンポーネントへのフィードバックを修正

---

packages/react-sandbox/package.json
packages/react/package.json
packages/theme/package.json
yarn.lock

- @chacoal-ui/react-sandbox: react-springを`peerDependencies`から`dependencies`に移動した。
- charcoalのユーザーが必ずしもreact-springを直接使うわけではないため。
- @charcoal-ui/react: react-springが`dependencies`にも`devDependencies`にも`peerDependencies`にも指定されていなかったので、`dependencies`に追加した。
- この影響でreact-springが@charocoal-ui/reactのbundleに含まれてしまっていた。
- @charcoal-ui/theme: polishedが`dependencies`に含まれていなかったので追加した。

dependencyの指定忘れを修正

---

.github/workflows/gh-pages.yml
.github/workflows/icons.yml
.github/workflows/test.yml
.github/workflows/version.yml

GitHub Actionsの各workflowファイル内でnodeのバージョンを書いていくとバージョンアップ時に全部書き換える必要があって大変なので `.node-version` から読み込むようにしました。
ref. https://github.com/actions/setup-node/blob/v3.5.1/docs/advanced-usage.md#node-version-file
CIが通ればok

GitHub Actionsの各workflowファイル内でnodeのバージョンを書くのをやめた

---

.github/dependabot.yml

GitHub Actionsのworkflowは一度設定するとactionsのバージョンアップを忘れがちなので、Dependabotでバージョンアップするようにしました。
c.f. [Keeping your actions up to date with Dependabot \- GitHub Docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
主な個人リポジトリには全部入れて動作確認しましたが、`v1.2.3` のようなバージョンだけでなく `v1` のようなメジャーバージョンのtagに対してもバージョンアップのPRが作られることを確認しました。
* 設定を入れた時のPR: https://github.com/sue445/terraform-gcp-template/pull/78
* Dependabotで実際に作られたPR: https://github.com/sue445/terraform-gcp-template/pull/79

Auto upgrade action version with dependabot

---

packages/react/src/components/Modal/index.tsx
packages/react/src/core/OverlayProvider.tsx
packages/react/src/index.ts

related: #118 #203
- `import { OverlayProvider } from '@charcoal-ui/react'` と書けるようにした
- 内容は `@react-aria/overlays` のものをそのまま
- `charcoal-ui/react` を使うにはついでに `react-aria/*` もインストールしないといけないという暗黙のルールを減らすため
長期的には `<CharcoalProvider>` のようなものを作るべきか悩むが、いったんこれで
Storybook ?
- ~~README やドキュメントに影響があることを確認した~~
- とりあえず doc comment に書いた（コンポーネントの個別の説明はいまは書く場所がない）

export OverlayProvider from @charcoal-ui/react

---

misc/postpublish.sh

yarn lerna version した際にタグが打たれるが、yarn lerna publish 後に tag が push されていなかった。
`misc/postpublish.sh` で `git tag origin --push` を呼ぶようにする。
次リリース時ににある

postpublish で tag を push する

---

packages/icons/src/loaders/CustomIconLoader.ts
packages/icons/src/loaders/PixivIconLoadError.ts

- minifyされるとエラー名がおかしくなるのを修正
- instanceofがうまく動かない問題を修正
- PixivIconLoadErrorが2重にならないように修正
- storybookで、ネットワークをオフライン状態にして確認

fix: PixivIconLoadErrorのエラー名とprototypeを修正

---

packages/icons-cli/package.json
packages/icons-cli/tsconfig.build.json
packages/icons-cli/tsup.config.ts
packages/react/package.json
packages/react/tsconfig.build.json
packages/react/tsup.config.ts
tsconfig.json
yarn.lock

ビルド高速化のためにtsupと`tsc --incremental`を導入した。このPRでは第一弾として、試験的にreactとicons-cliのみ移行した。
- microbundleをtsupに置き換えた
- tsupはesbuildのラッパー
- esbuildは設定が書きづらいのでtsupを使うことにした
- tscの`--incremental`フラグを有効にした
- 2回目以降の型チェックや`.d.ts`生成が高速になる
- cf. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#faster-subsequent-builds-with-the---incremental-flag
どちらもbreaking changeにならないはずです。
```sh
yarn build
```

ビルド高速化 (react, icons-cli)

---

packages/react/src/components/Checkbox/index.tsx
packages/react/src/components/DropdownSelector/Listbox.tsx
packages/react/src/components/DropdownSelector/index.tsx
packages/react/src/components/LoadingSpinner/index.tsx
packages/react/src/components/MultiSelect/index.tsx
packages/react/src/components/Radio/index.tsx
packages/react/src/components/Switch/index.tsx

charcoal-ui/reactのスタイルがFigmaと異なっている箇所を修正しました。
|component|before|after|
|-|-|-|
|Checkbox|<img width="81" alt="image" src="https://user-images.githubusercontent.com/29514424/215407928-954c77db-fe6d-4a90-8c2e-c7a1acd55a2e.png">|<img width="88" alt="image" src="https://user-images.githubusercontent.com/29514424/215405948-197d2624-559a-4602-a99d-ce72e1d4cbd1.png">|
|DropdownSelector|<img width="234" alt="image" src="https://user-images.githubusercontent.com/29514424/215408019-8100c7a0-e131-4678-9043-2dda7b6b8406.png">|<img width="240" alt="image" src="https://user-images.githubusercontent.com/29514424/215406057-cb053fc5-6c0b-464b-9e2b-6af9cb48639b.png">|
|LoadingSpinner|<img width="87" alt="image" src="https://user-images.githubusercontent.com/29514424/215408140-823aa6bc-41ef-4512-bf93-b52e2b6 …

fix: スタイルが適切に指定されていない箇所を修正

---

packages/react/src/components/DropdownSelector/Listbox.tsx

- dropdownselector の icon color に style があたってないのを修正
- storybook 

fix(react): fix wrong styles

---

packages/react/tsup.config.ts

Next.js環境で下記エラーが出るので回避策としてビルド後に変換を追加
```
TypeError: import_styled_components2.default.button is not a function
at Object.<anonymous> (/path/pixiv-web/node_modules/@charcoal-ui/react/dist/index.cjs:137:54)
```
関連: https://github.com/evanw/esbuild/issues/2581

fix: cjsをNext.js環境で使用できるように修正

---

packages/react/src/components/Modal/index.tsx
packages/react/src/core/CharcoalProvider.tsx
packages/react/src/core/ComponentAbstraction.tsx
packages/react/src/index.ts

特に tailwind を使うプロジェクトにおいて、`@charcoal-ui/react` を入れるには追加で styled のセットアップをしなければならないというのが導入の障壁になりがち。
そうでなくても、特定のコンポーネントを使うために `@react-aria/*` を各自で入れなければならない状況があって（ SSRProvider を export することで解決できてるとは言え ）ダルい。
`<CharcoalProvider>` というコンポーネントを作り、これで囲っておけばなんとなく `@charcoal-ui/react` を動かすのに必要な Context が提供されるようにする。
デメリットとして、使いもしない Context も bundle される（ SSR しないプロダクトも一旦 SSRProvider を読む ）とかが起こるというのはある

<CharcoalProvider> を作る

---

packages/react/src/components/Modal/index.tsx

- ModalをStrictModeに対応
- document.bodyをportalContainerに指定することで回避することができる
- Modalの表示でスクロールできないバグ修正
- Modalを開かなくてもレンダリングするだけで画面のスクロールができなくなるバグを修正
Storybook

fix: ModalをStrictModeに対応 + Modalの表示でスクロールできないバグ修正

---

.github/workflows/bundle-size.yml

bundle size を PR ごとに計測する仕組みを入れてみる（ preact 公式の作った Action ）
https://github.com/preactjs/compressed-size-action
純粋にライブラリの重さを意識できるし、また https://github.com/pixiv/charcoal/pull/226 のような「間違って dist に依存の依存が含まれてしまった」といったミスに気づくチャンスも増えるという期待もある。
いまだと 1 バイトでも増えたら報告の対象になるっぽいのでここは要調整かも。
あとデフォルトでは gzip した状態を比較するっぽい（圧縮前で比較したほうが良い？）
この PR にちゃんとしたコメントが来れば良い（ アクセストークンは特にセットアップしなくても動くはず ）。
push ごとのほうが良いか？と思ったが `on: [pull_request]` はふつうに PR 更新時にも発火するらしいので OK
https://zenn.dev/snowcait/articles/dc1851e421e600#pr-%E3%81%8C%E6%9B%B4%E6%96%B0%E3%81%95%E3%82%8C%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%AB%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B

bundle size を PR ごとに計測する仕組みを入れてみる

---

packages/react/src/components/Checkbox/index.story.tsx
packages/react/src/components/Checkbox/index.tsx

- https://github.com/pixiv/charcoal/issues/221
- storybook で確認
- `theme(o => o.typograpy(14))` を使うのをやめた
- negative margin を使用して line-height を打ち消している部分が 1 行のとき checkbox と高さを合わせる見た目の弊害になったため
- 実装は mantine の checkbox を参照した
- https://mantine.dev/core/checkbox/

feat(react): fix checkbox check icon position

---

packages/react/src/components/Switch/index.tsx

- `Switch`コンポーネントで用いられている`<input>`についているuser agent stylesheetのmarginを上書きして取り除く
- `grid-template-columns: auto 1fr`と`gap`の併用により、unlabeledな場合に必ず右端部に余白がついてしまうのを取り除く

fix: remove extra margins from `Switch`

---

.github/workflows/test.yml

CI 上でリポジトリの node-version と異なるバージョンの Node.js が意図せず使われているケースがある。
これのせいでビルドに失敗したのを見たので直したい
例: https://github.com/pixiv/charcoal/actions/runs/4220752310/jobs/7327328447
```
node:internal/crypto/hash:71
this[kHandle] = new _Hash(algorithm, xofLen);
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
```
とりあえず Node.js のバージョン指定に常に .node-version を使うように変える
CI が通るか

chore: prefer node-version-file always

---

packages/react/src/components/DropdownSelector/index.story.tsx
packages/react/src/components/DropdownSelector/index.tsx

- width: 100% にして wrapper で size 調整できるようにした
- https://github.com/pixiv/charcoal/issues/222
- storybook
dropdownselector の overlay がおかしくなるバグに関してはちょっと時間がかかりそうだったので別の PR にします

feat(react): dropdownselector の width を 100% にする

---

packages/styled/package.json
packages/styled/src/__snapshots__/index.test.tsx.snap
packages/styled/src/index.story.tsx
packages/styled/src/index.test.tsx
yarn.lock

ref: https://github.com/pixiv/charcoal/issues/256
styled のメンテナビリティをあげたいのでリファクタリングをしたいが、現状の挙動がテストされてない。
あんまり丁寧なテストはないが、とりあえず storybook のレンダリング結果をスナップショットテストして回帰テストとして使う
CI が通るかどうか

@charcoal-ui/styled に簡単なスナップショットテストを追加

---

packages/react/src/components/TagItem/index.tsx

- tag item が inactive 時の background color が間違っていたので修正
- storybook

fix(react): fix wrong tag item style

---

packages/react/src/components/DropdownSelector/DropdownPopover.tsx

- DropdownSelectorのportalContainerをdocument.bodyに設定
- Next.jsで正常に動作するようにするため（SSR時にOverlayを開いていないことを想定）

fix: portalContainerをdocument.bodyに設定

---

.github/workflows/icons.yml

icons-cli は Figma に変更があったらいま毎日 PR を送ってくる。
現状のリリース頻度的にこれは週一でも良い（ そうでないと同じ内容の PR が何度も作られてしまいがち ）。
週に１回リリースをする際にこれをレビューするみたいな運用でも良いかも

icons-cli の実行を週一にする

---

.github/workflows/docs-hosting-pr.yml

#277 の修正
https://github.com/pixiv/charcoal/blob/773269152abdd0c2574c8f5a416df19b1a3465ac/.github/workflows/docs-hosting-pr.yml#L47-L52 での認証には https://github.com/pixiv/charcoal/blob/564fef976cf3f213a951b493b51aadb3224ae49c/.github/workflows/docs-hosting-pr.yml#L11 の設定が必要なのですが、 https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token によるとforkされたリポジトリのPRだと `id-token` は最大でも `read` しか付与できないのが原因だと思われます。
`pull_request_target` にすることでおそらく回避できるとは思うのですが、それだとGitHub ActionsのSecurityを犠牲にして好ましくないためpixiv org外からのPullRequestでWorkflowを実行させないようにしています 😢 
ref. https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
GitHub Actions
Close #277

fix: Skip docs-hosting-pr workflow when PullRequest from forked repo

---

docs/package.json
docs/yarn.lock

https://github.com/pixiv/charcoal/pull/269
```
Failed to compile.
./node_modules/@charcoal-ui/styled/src/util.ts:97:22
Type error: No overload matches this call.
Overload 1 of 2, '(o: {}): string[]', gave the following error.
Argument of type '_' is not assignable to parameter of type '{}'.
Type 'T' is not assignable to type '{}'.
Overload 2 of 2, '(o: object): string[]', gave the following error.
Argument of type '_' is not assignable to parameter of type 'object'.
Type 'T' is not assignable to type 'object'.
95 |   _ extends T = T
96 | >(obj: _) {
>  97 |   return Object.keys(obj) as unknown as (keyof T & string)[]
|                      ^
98 | }
99 | 
100 | export interface ReadonlyArrayConstructor {
Error: Process completed with exit code 1.
```

https://github.com/pixiv/charcoal/pull/269 の CI が通らない件調査

---

packages/react/src/components/TagItem/index.story.tsx
packages/react/src/components/TagItem/index.tsx

- https://github.com/pixiv/charcoal/issues/263
- これの対応として話題に上がった tagitem にだけ className を付けた
- これ以外の component にもつける場合には一括でつける。forwardRef に関しては内部のどこの component に ref を張るのかは決めないといけない気がする 
- storybook

chore(react): add classname to tagitem props

---

packages/react/src/components/Modal/ModalPlumbing.tsx

- padding を 24 から 16 に変更した
- https://github.com/pixiv/charcoal/issues/265 
- stroybook 

chore(react): change padding 24 -> 16

---

packages/react/src/components/DropdownSelector/index.story.tsx
packages/react/src/components/SegmentedControl/index.story.tsx
packages/react/src/components/SegmentedControl/index.tsx

- SegmentedControlにラベルの付与を追加
- storyのlabelに関する警告を修正

fix: SegmentedControlにラベルの付与を追加

---

docs/src/components/GlobalStyle.tsx
docs/src/components/InlineCode.tsx
docs/src/components/NavList.tsx
docs/src/components/Table.tsx
docs/src/pages/@charcoal-ui/icons/element.page.tsx
docs/src/pages/@charcoal-ui/icons/extend.page.tsx
docs/src/pages/@charcoal-ui/icons/quickstart.page.tsx
docs/src/pages/@charcoal-ui/icons/react.page.tsx
docs/src/pages/@charcoal-ui/icons/ssr.page.tsx
docs/src/pages/@charcoal-ui/react/_components/ApiTable.tsx
docs/src/pages/@charcoal-ui/react/ssr.page.tsx
docs/src/utils/string.ts

`@charcoal-ui/icons` の使い方に関するページを追加。
だいたい旧ドキュメントサイトやREADMEの転記だが、2.0.0 以降の実態に合わせた。
`icon-files` や `icons-cli` のドキュメントも書くか考えたが、メンテナしか知らなくていいよなと思って一旦除いている（迷ってる）

@charcoal-ui/icons のドキュメントのページを追加

---

docs/src/pages/@charcoal-ui/react/TextField/sections.tsx
packages/react/src/components/TextField/index.tsx

fix: #248 
ツリー構造を変えないためにprefixにz-indexを追加
docs

fix: textFieldのprefixがinputの背景色の影響を受ける #248

---

packages/styled/src/TokenInjector.tsx
packages/styled/src/__snapshots__/index.test.tsx.snap
packages/styled/src/builders/border.ts
packages/styled/src/util.ts

fixes: https://github.com/pixiv/charcoal/issues/242

styled: theme.border の色を CSS Variables で扱うようにする

---

packages/react/src/components/Radio/index.tsx

- `<RadioInput>` のラジオボタン部分も cursor: pointer となるように修正した
- Storybook
https://github.com/pixiv/charcoal/assets/20609120/fdca55a9-6f59-4e51-bee5-ef94a617b2a3

fix: <RadioInput> のラジオボタンも cursor: pointer となるように修正した

---

docs/src/pages/@charcoal-ui/tailwind-diff/quickstart.page.tsx

- tailwind-diff のドキュメントのnpmjsのバッジのラベルが `@charcoal-ui/icons` だったのを `@charcoal-ui/tailwind-diff` へ修正しました。
CIから発行されるURLの `/@charcoal-ui/tailwind-diff/quickstart/` を見る

fix: npmjsバッジのラベルが @charcoal-ui/icons のままだったのを修正

---

docs/src/pages/@charcoal-ui/react/_components/Previews.tsx
docs/src/pages/v3.0.0-guide.page.tsx

- v3.0.0でreact17に変えた旨を追記
- コンテンツが横にスクロール可能になってしまう問題を修正
- https://pixiv-charcoal-web--pr298-v3-0-0-ypwjowl4.web.app/@charcoal-ui/styled/bg/ などPreviewDivがあるページでコンテンツエリアをはみ出していた

ドキュメントの修正と更新

---

packages/react/src/components/Modal/index.tsx

fix: fix misleading `<Modal>` usage

---

docs/src/pages/@charcoal-ui/react/TextArea/apiData.tsx
docs/src/pages/@charcoal-ui/react/TextArea/index.page.tsx
docs/src/pages/@charcoal-ui/react/TextField/apiData.tsx
docs/yarn.lock
packages/react/src/_lib/compat.ts
packages/react/src/components/TextArea/index.tsx
packages/react/src/components/TextField/index.tsx

TextArea は `<textarea>` の、TextField は `<input>` の属性を基本的に受け付けるようにしたい（完全に一緒ではない箇所もある）

TextArea と TextField は通常のhtmlと同じ属性を受け付ける

---

docs/yarn.lock
packages/react/src/components/DropdownSelector/index.tsx

- usePopoverの副作用が出ないように修正
- usePopoverの副作用でDropdownSelectorを表示しただけでスクロールできなくなっていた
before
https://pixiv-charcoal-web--pr298-v3-0-0-ypwjowl4.web.app/@charcoal-ui/react/DropdownSelector/
after
https://pixiv-charcoal-web--pr342-toshusai-fix-popover-ko599eol.web.app/@charcoal-ui/react/DropdownSelector/

v3.0.0: usePopoverの副作用が出ないように修正

---

docs/src/components/NavList.tsx
docs/src/pages/@charcoal-ui/react/TextArea/apiData.tsx
docs/src/pages/@charcoal-ui/react/TextArea/index.page.tsx
docs/src/pages/@charcoal-ui/react/TextArea/sections.tsx
docs/src/pages/@charcoal-ui/react/TextField/apiData.tsx
docs/src/pages/@charcoal-ui/react/TextField/index.page.tsx
docs/src/pages/@charcoal-ui/react/TextField/sections.tsx
docs/src/pages/v3.0.0-guide.page.tsx
docs/yarn.lock
packages/react/src/_lib/index.ts
packages/react/src/components/DropdownSelector/ListItem/index.tsx
packages/react/src/components/TextArea/TextArea.story.tsx
packages/react/src/components/TextArea/index.tsx
packages/react/src/components/TextField/TextField.story.tsx
packages/react/src/components/TextField/index.tsx
packages/react/src/index.ts

Reverts pixiv/charcoal#286
closes: #164
ref: #211 https://github.com/pixiv/charcoal/issues/209
- storybook 上で TextField の中身を分割して TextField と TextArea に分けた
- storybook
- めちゃくちゃ破壊的変更なのでこれを merge したあとどこの version に混ぜるかは考えたほうが良さそうだと思いました。

TextField を TextField と TextArea に分ける

---

packages/react/src/components/TextField/index.story.tsx

- TextField の storybook にある PrefixIcon に使用されている icon のカラーを `text4` から `text3` に変更
- storybook

chore(react): change icon color

---

packages/react/src/components/TextArea/index.tsx
yarn.lock

- TextAreaのフォーカスアニメーションを修正
- focusアウト時のアニメーションが無くなっていた
before:
https://pixiv-charcoal-web--pr298-v3-0-0-ypwjowl4.web.app/@charcoal-ui/react/TextArea/

v3.0.0: TextAreaのフォーカスアニメーションを修正

---

packages/react/src/components/Modal/index.tsx

https://github.com/pixiv/charcoal/commit/73b17f3fe3cc8f741825036a7ae2f475f18aabc7#r121234349 を直す
- `<Modal>`のルートについている上下の余白により、`<ModalHeader>`や`<ModalButtons>`と併用したときに壊れてしまう
- 上下のpaddingをなくした

fix: remove `<Modal>` vertical padding

---

packages/react/src/components/DropdownSelector/index.story.tsx
packages/react/src/components/DropdownSelector/index.tsx

- DropdownButtonに `type=button` をつけた
- 明示しないと `type=submit` となり、フォーム内でDropdownSelectorを使ったときに選択肢を選んだだけでSubmitされてしまうため
- #355 対応
Storybookで `localhost:6006/?path=/story/dropdownselector--in-form-tag` をチェック  
`type="button"` を指定することで `<form>` タグ内に配置されていてもページ遷移が起きなくなることを確認しました。

DropdownButtonに type=button をつける

---

packages/react/src/components/Modal/index.tsx

デスクトップの場合、Modalの大きさに関わらずXYのスクロールバーが表示されていたため
- ModalBackgroundのoverflowプロパティを`scroll`から`auto`へ変更

fix: Modalの大きさによってスクロールバーが非表示になるように修正

---

.github/workflows/publish.yml

- git config user.name、git config user.emailが無くて止まったので追加

fix: add git config user.name and git config user.email

---

.github/workflows/publish.yml

- YARN_CHECKSUM_BEHAVIOR="update" にすると yarn.lock を更新できるようになる

fix: set YARN_CHECKSUM_BEHAVIOR for yarn.lock update

---

packages/react/src/components/DropdownSelector/index.tsx

- dropdownselector から border を削除
- storybook 

chore(react): remove dropdown selector border

---

packages/react/src/components/FieldLabel/index.tsx

- FieldLabel の RequiredLabel の色を figma と合わせた
- storybook 

chore(react): fix wrong text color

---

.github/workflows/test.yml
packages/react/jest.config.mjs
packages/react/src/components/Checkbox/performance.test.tsx

- checkbox を 1000 個 rendering するのにかかる時間を計測する test を追加
- github actions 時には performance.test.tsx が動かないようにする設定を追加
- 手元で `yarn jest packages/react/src/components/Checkbox/performance.test.tsx ` が動作することを確認
[![Image from Gyazo](https://i.gyazo.com/eaf93d2fd45a908f9af51cab0085cdbd.png)](https://gyazo.com/eaf93d2fd45a908f9af51cab0085cdbd)

Checkboxのパフォーマンステスト

---

.github/workflows/test.yml

- storybook 7.4アプデで不調になったstorybookのviteビルドを `test.yml` から削除しました。
- 直し方がわかったら直します

chore: comment out build-storybook-vite

---

packages/react-sandbox/src/components/Pager/index.story.tsx
packages/react-sandbox/src/components/Pager/index.tsx

- react-sandboxのpagerに `pageRangeDisplayed` という props を追加しました
- Pager の中に一度に表示される要素の数を調整することができます
Storybook

react-sandbox の Pager に要素の数を調節できるpropsの追加

---

.github/workflows/gh-pages.yml
.github/workflows/test.yml

- mainでのみ走るworkflowの gh-pages.yml のstorybookコマンドを置き換えた

wip: build-storybookが壊れているのを直す

---

packages/react/src/components/Checkbox/index.story.tsx
packages/react/src/components/Checkbox/index.tsx

- Checkboxにinvalid属性を追加（[Figma](https://www.figma.com/file/ZfumEAYeBUubytKhRAfHg8/Charcoal---Web-Components-(Community)?node-id=32%3A28&mode=dev)）
- Storybookを更新
Storybookで確認できます。

feat: Checkboxコンポーネントのinvalid状態を実装

---

packages/react/src/components/Modal/ModalPlumbing.tsx
packages/react/src/components/Modal/__stories__/BottomSheetOverflowStory.tsx
packages/react/src/components/Modal/__stories__/InternalScrollStory.tsx
packages/react/src/components/Modal/index.story.tsx
packages/react/src/components/Modal/index.tsx

- bottomSheetのコンテンツがオーバーフローした際に適切にスクロール可能になるように修正
- Focusがモーダル内の最後で止まるのを修正
- useDialogのコンポーネントを分離
- モーダル上下の余白を24pxから40pxに修正
- bottomSheetの時のタイトルの高さを64pxから48pxに修正
- 内部スクロールの例を追加

fix: Modalの挙動と外観を修正

---

packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
packages/react/src/components/TextArea/index.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
packages/react/src/components/TextField/index.tsx

- 仕様に合わせてTextFieldおよびTextAreaのassistiveTextの色をtext1からtext2に変更

fix: assistiveTextの色をtext1からtext2に変更

---

packages/react/src/components/TextField/TextField.story.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
packages/react/src/components/TextField/index.tsx
packages/react/src/components/TextField/useFocusWithClick.tsx

- textFieldのprefix, suffix構造を更新
- prefix, suffixの幅をResizeObserverで計算しないように変更
- theme()を利用しないように変更
- prefixをクリック時にfocusするように修正
- デザイン修正

feat: textFieldの構造を更新

---

packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
packages/react/src/components/IconButton/index.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot

- `<IconButton>`の`attrs()`から、width、height、またthemeなどのプロパティまでもがDOM Elementに渡されていたのを修正した

fix: `<IconButton>`でDOM Elementに不要な属性が渡されるのを防ぐ

---

packages/react/src/components/Button/__snapshots__/index.story.storyshot
packages/react/src/components/Clickable/__snapshots__/index.story.storyshot
packages/react/src/components/Clickable/index.tsx
packages/react/src/components/DropdownSelector/Popover/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot

- Clickableにtext-decoration: noneをつける
- Buttonなどに to が指定されて `<a>` になった時に下線が引かれないようにしたい

Clickableにtext-decoration: noneをつける

---

packages/react/src/components/TextField/TextField.story.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
packages/react/src/components/TextField/index.tsx

- TextFieldのprefixの余白を修正
- storyを利用例に近い形式に更新

fix: TextFieldのprefixの余白を修正

---

packages/theme/src/default.ts

fix: dark themeのsurface7の色が間違っている

---

docs/src/pages/_app.page.tsx
docs/tailwind.config.js

- tailwindをdocsで効くようにした
- preflightを無効にした
- リセットCSSが全てのページに効いてしまうため

docsにtailwindcssを設定してpreflightを無効

---

packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
packages/react/src/components/TagItem/index.tsx

- TagItem コンポーネントから styled 記法を抜く
- snapshot

remove styled from tag item

---

packages/theme/src/default.ts
packages/utils/src/index.ts

- convert `polished` import path to full path
- https://github.com/styled-components/polished/issues/478
1. We should avoid parsing/computing colors/styles at runtime as much as we can
2. if we really need, use `color-mix` https://caniuse.com/?search=color-mix if available
3. it's not easy to do currently due to `applyEffect` accepts any unknown effect from custom theme
4. maybe deprecating the concept of runtime `effect` at all?

fix: sub-module import polished

---

docs/src/components/NavList.tsx
docs/src/components/tailwind-config/typography/HalfLeading.tsx
docs/src/components/tailwind-config/typography/Sizes.tsx
docs/src/components/tailwind-config/typography/utils.ts
docs/src/pages/@charcoal-ui/tailwind-config/typography.page.tsx

- tailwind-configのTypographyのsizeとhalf leading cancellationが見れるdocs追加

tailwind-configのTypography docs追加

---

packages/react/src/components/Button/StyledButton.tsx
packages/react/src/components/Button/index.tsx
packages/react/src/components/Button/lib/variantToBackground.tsx
packages/react/src/components/Button/lib/variantToFont.tsx

- Refactored the Button component code. Divided the code that was combined into one file and made one file smaller.

refactor: split the file into smaller

---

packages/react/src/components/DropdownSelector/DropdownMenuItem.tsx
packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.story.tsx
packages/react/src/components/DropdownSelector/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot

- Implemented truncation of long texts to display them in a single line.
- Added padding for list items with multi-line text.

feat: enable long text in DropdownSelector

---

packages/react/src/components/Button/__snapshots__/index.story.storyshot
packages/react/src/components/Button/index.story.tsx

- buttonのstoryをCSF3にした
storybook

/reactのStorybook CSF3化 button編

---

packages/react/src/components/LoadingSpinner/LoadingSpinnerIcon.story.tsx
packages/react/src/components/LoadingSpinner/index.story.tsx
packages/react/src/components/LoadingSpinner/index.tsx

- LoadingSpinnerのstoryをCSF3にした
- IconLoadingSpinnerのPropsをinterfaceではなくtypeを使って宣言するようにした
- よく分からないエラーが出たため
- 

/reactのStorybook CSF3化 LoadingSpinner編

---

packages/react/src/components/Modal/index.story.tsx

- Modal/index.story.tsx update to csf3

Modal story update to csf3

---

packages/react/src/components/Checkbox/__snapshots__/index.story.storyshot
packages/react/src/components/Checkbox/index.tsx
packages/react/src/components/Radio/__snapshots__/index.story.storyshot
packages/react/src/components/Radio/index.tsx

- Changed the cursor style to default for Radio and Checkbox when disabled.
- This change was made to provide a user experience similar to that of buttons.
- Correctly applied the readonly attribute to the Checkbox input.

fix: cursor to default when Radio and Checkbox are disabled

---

package.json
packages/esbuild-plugin-styled-components/README.md
packages/esbuild-plugin-styled-components/package.json
packages/esbuild-plugin-styled-components/src/index.ts
packages/esbuild-plugin-styled-components/tsconfig.build.json
packages/esbuild-plugin-styled-components/tsconfig.json
packages/react-sandbox/package.json
packages/react-sandbox/tsup.config.ts
packages/react/package.json
packages/react/tsup.config.ts
yarn.lock

- `@charcoal-ui/esbuild-plugin-styled-components`パッケージを追加した
- [`babel-plugin-styled-components`](https://github.com/styled-components/babel-plugin-styled-components)と同様に、hydration errorを防ぐID付与やスタイルのminificationなどを行う

build: apply babel-plugin-styled-components on build

---

docs/src/pages/@charcoal-ui/react/Switch/index.page.tsx

- fix: #467 
- The exact cause is unclear, but as a temporary workaround, we have enclosed it in a div.

docs: fix switch layout

---

packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/index.tsx
packages/react/src/components/Modal/useCustomModalOverlay.tsx

- Fix: The modal closed when clicking the scrollbar on the modal background.
We want to enable scrolling on the modal background, but `useModalOverlay` (specifically, `useOverlay` within it) detects pointer events on the scrollbar. Therefore, to prevent this issue, we need to override `shouldCloseOnInteractOutside` in `useModalOverlay`.

Fix: The modal closed when clicking the scrollbar on the modal background.

---

packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/TextArea/index.tsx
packages/react/src/components/TextField/TextField.story.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
packages/react/src/components/TextField/index.tsx

- `props` are not passed to the input element. They are merged with `ariaInputProps`.

Fix: Input props are not passed to the `<input />`

---

.github/workflows/docs-hosting-pr.yml
.gitignore
docs/src/components/NavList.tsx
packages/styled/src/__snapshots__/index.story.storyshot
packages/styled/src/__snapshots__/index.test.tsx.snap
packages/styled/src/index.story.tsx

- Added the storybook preview in PR.
- Ignored `*.log` for firebase cli.
- Supported dark theme of the `themeUtils` story.

CI: Added the storybook preview in PR.

---

packages/react/src/components/Button/index.css

- Added `box-sizing: border-box;` to `Button`.
- The width of the button cannot be set without considering the padding when `as="a"`.
- Simplified the `padding` property.
ex.
```tsx
<Button fullWidth as="a">Link</Button>
```

Fix: Resolved unexpected button width issue when `as="a"`.

---

.storybook/test-runner.ts
jest.setup.ts
packages/react/src/components/MultiSelect/index.tsx

- Replace multiselect icon with icon component from `<pixiv-icon>`

Replace multiselect icon with icon component

---

.github/workflows/test-storybook.yml

v4 でも VRT を実行するように

---

packages/react-sandbox/tsconfig.build.json
packages/react/tsconfig.build.json

- exclude dts generation of stories and tests
Currently stories and tests dts are generated and distributed inside the package but it's not necessary. 
It 
1. makes review harder to do (https://app.renovatebot.com/package-diff?name=@charcoal-ui%2freact&from=3.9.1&to=3.10.0) 
2. mess the import suggestions

fix: skip build story and test dts

---

.storybook/docs-container.tsx
.storybook/preview.js

- docs の表示をテーマに合わせて変わるように変更
- storybook
|light|dark|
|---|---|
|[![Image from Gyazo](https://i.gyazo.com/3f79a8a7e34d6860ff49d2cb9854bc87.png)](https://gyazo.com/3f79a8a7e34d6860ff49d2cb9854bc87)|[![Image from Gyazo](https://i.gyazo.com/1e386aca71d9794adcacdc4878c34eab.png)](https://gyazo.com/1e386aca71d9794adcacdc4878c34eab)|

chore(storybook): apply docs theming

---

packages/react/src/components/Radio/index.story.tsx
packages/react/src/components/Radio/index.tsx

- allow `RadioGroup` to accept generic `Value`type for `value` and `onChange` typing. I didn't find a easy way to infer type for this without generic. This should be backward compatible.

feat: allow type radio group value

---

docs/src/pages/@charcoal-ui/react/TextArea/apiData.tsx
docs/src/pages/@charcoal-ui/react/TextField/apiData.tsx
docs/yarn.lock
packages/react/package.json
packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
packages/react/src/components/TextArea/index.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
packages/react/src/components/TextField/index.tsx
yarn.lock

- Modify props to inherit properties from the native element.
- Added a getCount prop to calculate text length using a custom function.
- Removed useTextField.
- Storybook

feat: update TextField and TextArea API

---

packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
packages/react/src/components/IconButton/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/index.tsx
packages/react/src/index.ts

- add `closeButtonAriaLabel` for `Modal` and `aria-hidden` for pixiv-icon inside.
- rename and export `ModalCloseButton`
Before:
After:

feat: add modal button aria label and export ModalCloseButton

---

docs/src/pages/@charcoal-ui/react/Modal/apiData.tsx
docs/yarn.lock

- Fix for `closeButtonAriaLabel` in Modal docs

Fix for closeButtonAriaLabel in Modal docs

---

docs/src/pages/@charcoal-ui/react/ssr.page.tsx
docs/yarn.lock
packages/react/README.md
packages/react/src/core/SSRProvider.tsx

Render SSRProvider as Fragment if react version >= 18 to avoid the `In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.` warning.
Similar code: https://github.com/search?type=code&q=%22import+%7B+version+%7D+from+%27react%27%22&p=1
Commit history on react side: https://github.com/facebook/react/commits/main/packages/shared/ReactVersion.js

fix: avoid SSRProvider after react 18

---

packages/icons/src/PixivIcon.ts
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/index.story.tsx

- fix `waitUntilVisible` to contain the fix in https://github.com/vueuse/vueuse/pull/3365
- In Chromium based browsers, multiple entries can be returned in a single callback even only called `observe()` once.
- Found this is more likely to happen if the element's parent has css transform somehow? e.g. Modal/Sidebar
- Related implementation but not found so mush useful info. https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/intersection_observer/intersection_observation.cc;l=36

fix: pixiv-icon waitUntilVisible condition

---

firebase.json

- firebase redirect 
- `firebase emulator --only hosting`

chore: add firebase redirect settings for docs

---

packages/pullrequest-cli/package.json
packages/token-cli/package.json
packages/token-cli/pixiv-dark.config.js
packages/token-cli/pixiv-light.config.js
packages/token-cli/src/createToken.ts
packages/token-cli/src/transformer/index.js
packages/token-cli/src/transformer/index.test.js
yarn.lock

- fix `pixiv-dark.config.js`
- I used to include the mode name in the object name when the mode name is anything other than 'default'. However, I stopped doing that because it made name resolution with Style Dictionary impossible.

fix token cli

---

packages/token-cli/src/transformer/index.js
packages/token-cli/src/transformer/index.test.js

- Fixed an issue where hyphens were being unnecessarily removed in primitive tokens that included negative values in the name.

fix(token-cli): primitive token named negative value case

---

packages/token-cli/src/transformer/index.js
packages/token-cli/src/transformer/index.test.js

- fixed an issue where hyphens were being unnecessarily removed in primitive tokens that included negative values in the name.

fix(token-cli): primitive token named negative value case in v4

---

packages/react/src/components/Modal/index.tsx
packages/react/src/components/Modal/useCustomModalOverlay.tsx

- `Modal`がサーバーサイドで利用できない問題を修正しました。
- Next.jsなどのフレームワークでSSRできるようにするためです。

fix: modalがサーバーサイドで利用できない問題を修正

---

packages/react/package.json
packages/react/tsup.config.ts

- Added an `@layer charcoal { ... }` output in `@charcoal-ui/react` via esbuild plugin.
- Motivations:
1. Easier management for css cascading
- especially important for migrating from v3 with less breakage
- more control on the user side for adjusting orders.
2. Already good enough browser coverage
- https://caniuse.com/?search=%40layer
- https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
- better than requiring users to do something similar via modifying their build setup.
- better than `@import "index.css" layer(charcoal);`

feat(@charcoal-ui/react): add @layer charcoal output for css output

---

packages/styled/src/helper.ts

- rename useTheme parama from key to localstorageKey
- modify theme type to be `"light" | "dark" | undefined`

fix: rename use theme key and update type

---

packages/tailwind-config/README.md

- `tailwind-config/README.md`のリンクが切れていたので修正しました。

docs(tailwind-config): tailwind-config/README.mdのリンク切れを修正

---

packages/icons/package.json
yarn.lock

- fix(@charcoal-ui/icons): bump dompurify to 2.5.7

fix: bump dompurify

---

.github/workflows/icons.yml

- icons-cliをmain以外のブランチで動かした時、PRのベースブランチが適切に変わるように変更しました
#638 
https://github.com/pixiv/charcoal/actions/runs/11358427793

feat(icon-workflow): Enable creation of PRs to the base branch

---

packages/icons/src/PixivIcon.ts
packages/icons/src/loaders/CharcoalIconFilesLoader.ts
packages/icons/src/loaders/CustomIconLoader.ts
packages/icons/src/loaders/Loadable.ts
packages/icons/src/loaders/index.ts

- Since style and known icons are fully controlled by us, it should be safe to skip dom purify in these cases.
- Lazy import and keep sanitizing custom icons so this should not be a breaking change. 

Feat: skip dom purify for trusted content

---

packages/icons/package.json
packages/icons/src/PixivIcon.ts
packages/icons/src/loaders/CharcoalIconFilesLoader.ts
packages/icons/src/loaders/CustomIconLoader.ts
packages/icons/src/loaders/Loadable.ts
packages/icons/src/loaders/index.ts
yarn.lock

- Further work from https://github.com/pixiv/charcoal/pull/393. Remove dompurify from v4 for reducing bundle size. Users should sanitize svg contents before passing to charcoal.

fix!(@charcoal-ui/icons): remove dompurify from v4.

---

packages/react/src/components/TextField/index.tsx

- classNameをリレーさせるために、`useClassNames`の引数に`className`を追加した。
`TextField`はpropsとして`className`を受け取っているが、それを渡している部分がなく、`styled()`などで上書きすることができない状態になっていた。

fix: pass down className prop

---

packages/token-cli/src/createToken.ts
packages/token-cli/src/figma/index.ts

- 使わないtokenの残りが出現することがあり、出力を見ないで対処することが困難なためPR上で意図しないtoken出力を確認できるようにする

tokenが参照できない時、warnを出して処理を続けるようにする

---

packages/token-cli/src/createToken.ts
packages/token-cli/src/figma/index.ts

(v4) tokenが参照できない時、warnを出して処理を続けるようにする

---

packages/react/src/components/MultiSelect/__snapshots__/index.story.storyshot
packages/react/src/components/MultiSelect/context.ts
packages/react/src/components/MultiSelect/index.css
packages/react/src/components/MultiSelect/index.story.tsx
packages/react/src/components/MultiSelect/index.test.tsx
packages/react/src/components/MultiSelect/index.tsx
packages/react/src/index.ts

- Revert "feat: remove MultiSelect"
- feat: refactor multiSelect to css
- fix: css order by stylelint
- fix: remove extra props spreading

fix: revert remove multiSelect

---

.github/workflows/publish.yml
.prettierignore
.storybook/src/v4.0.0.mdx
lerna.json
packages/esbuild-plugin-styled-components/package.json
packages/foundation/package.json
packages/icon-files/package.json
packages/icons-cli/package.json
packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/tailwind-diff/package.json
packages/theme/package.json
packages/token-cli/package.json
packages/utils/package.json
yarn.lock

v4 release note

---

packages/react-sandbox/src/components/HintText/index.story.tsx
packages/react-sandbox/src/components/HintText/index.tsx

- タイトルの通り
- 分割可能でない単語の例として長いメールアドレスなどがある

分割可能でない単語がHintTextに含まれていたときにあふれないようにする

---

packages/react/src/components/Clickable/index.tsx
packages/react/src/index.ts

- fix: restore clickable element type

fix: restore ClickableElement type

---

.storybook/test-runner.ts
packages/react/docs/TokenV2Demo.story.tsx
packages/react/docs/__snapshots__/TokenV2Demo.story.storyshot

- Theme/token V2 demo の snapshot を更新
- test-runner で画像をマスクするように
- vitest snapshot
- test-runner

Theme/token V2 demo の snapshot を更新

---

.github/workflows/icons.yml

- icons-cliを動かすActionで、PRを作るときのtarget branchをActionを実行したブランチになるようにしました
- v4とv3の両方でiconsを更新するため
- 実行例: #687 

icon更新をmain以外のブランチに対しても行えるようにする

---

.github/workflows/test-storybook.yml

- ubuntu-latestが24.04になったことにより必要な依存がなくなってこけるようになったようなので、22.04固定に変更しました
- success: https://github.com/pixiv/charcoal/actions/runs/12803670787/job/35696732205?pr=692
- failure: https://github.com/pixiv/charcoal/actions/runs/12803602132/job/35696546248

playwrightのinstallでこけてるの直す

---

.storybook/src/v4.0.0.mdx
packages/react/src/components/Button/index.tsx
packages/react/src/components/Button/styledButtonTypeTest.d.tsx
packages/styled/src/styledButtonType.d.tsx

- **fix: try support styled button**
- ⚠️  技術的に破壊的変更ですが、修正とみなしてminorとしてリリースします

fix: limit styled button type

---

packages/icons/src/SSR.mdx

chrome 133よりattr numberの挙動が変わってないほうが無難

fix: update unsafe non guideline scale ssr guide

---

packages/react/src/components/TextField/index.tsx
packages/react/src/components/TextField/text-field.test.tsx

- TextField component の prefix, suffix の表示条件を基に戻した
- test
- storybook

chore(react): fix text field prefix, suffix visible condition

---

packages/icons/src/index.ts
packages/react-sandbox/src/components/TextEllipsis/helper.ts
packages/react-sandbox/src/components/icons/DotsIcon.tsx
packages/react-sandbox/src/components/icons/WedgeIcon.tsx
packages/react-sandbox/src/foundation/hooks.ts
packages/react/src/_lib/index.ts
packages/react/src/components/Button/index.tsx
packages/react/src/components/Clickable/index.tsx
packages/react/src/components/DropdownSelector/ListItem/index.tsx
packages/react/src/components/DropdownSelector/MenuList/MenuListContext.ts
packages/react/src/components/DropdownSelector/Popover/index.tsx
packages/react/src/components/IconButton/index.tsx
packages/react/src/components/Modal/useCustomModalOverlay.tsx
packages/react/src/components/Radio/RadioGroup/index.tsx
packages/react/src/components/TagItem/index.tsx
packages/react/src/components/TextField/useFocusWithClick.tsx
packages/react/src/core/SetThemeScript.tsx
packages/styled/src/index.test.tsx

- support react 19
- https://react.dev/blog/2024/04/25/react-19-upgrade-guide

feat: react 19 codemod

---

package.json

- fix 4.3 beta install due to currently lerna publish does not support `workspace:` in peerDependencies https://github.com/lerna/lerna/issues/3671

fix: use pnpm publish

---

.husky/commit-msg

```
husky - DEPRECATED
Please remove the following two lines from .husky/commit-msg:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```

fix: husky warning

---

.github/workflows/publish.yml

- tagの作成追加してpushと一緒にpublish後に移動した

fix: move push command after publish

---

.github/workflows/icons.yml
packages/icons-cli/package.json

- `pnpm exec icons-cli` のように、icons-cliがpnpm環境下で正常に実行されるよう、workflowファイルを修正しました。

fix: pnpm exec icons-cli

---

packages/theme/src/docs/ThemeColors.tsx

- fix Storybook preview hooks can only be called inside decorators and story functions.

fix: ThemeColor doc display

---

packages/icons-cli/src/figma/FigmaFileClient.ts

- PDFファイルはバイナリのままダウンロードする必要があるため、gotに `responseType: 'buffer` を追加
- コンテンツがある領域が切り取られるようになっていたため、 fileImagesの取得時に `use_absolute_bounds: true` を追加

icons-cli: fix pdf export

---

.github/workflows/publish.yml
lerna.json
packages/esbuild-plugin-styled-components/package.json
packages/foundation/package.json
packages/icon-files/package.json
packages/icons-cli/package.json
packages/icons/package.json
packages/pullrequest-cli/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/tailwind-diff/package.json
packages/theme/package.json
packages/token-cli/package.json
packages/utils/package.json

- npmjsに設定しているリリースタグをgitにも設定するのをやめました
- latestやbetaは頻繁に更新され、gitのtagとしての運用が難しいと判断したため
https://github.com/pixiv/charcoal/actions/runs/15106431448/job/42456034578
https://github.com/pixiv/charcoal/releases/tag/v4.6.1-beta.0

chore: remove adding release tag to git

---

packages/react/src/index.ts

- export LoadingSpinnerIconHandler type since some users are importing this from dist

fix: export LoadingSpinnerIconHandler type

---

packages/react/src/index.ts

- exporting HintText from react package

fix: export hint text

---

packages/react/src/components/HintText/index.tsx

- make context prop default to 'section'

fix: HintText make context prop optional

---

packages/tailwind-config/src/icons.ts

- This is technically breaking change but the tailwind icons are unstable in v4.

fix: make tw classnames lowercase
