packages/foundation/package.json
packages/icons-cli/package.json
packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/tailwind-diff/package.json
packages/theme/package.json
packages/utils/package.json

- package.json に repository を追加

package.json に repository を追加

---

.storybook/global.css
.storybook/main.js
.storybook/postcss.config.js
.storybook/preview.js
.storybook/tailwind.config.js
.storybook/theme-decorator.tsx
package.json
packages/tailwind-config/package.json
packages/tailwind-config/src/_lib/compat.ts
packages/tailwind-config/src/docs/colors/Colors.tsx
packages/tailwind-config/src/docs/colors/TextBgColor.story.tsx
packages/tailwind-config/src/docs/colors/TextColors.tsx
packages/tailwind-config/src/docs/colors/index.story.mdx
packages/tailwind-config/src/docs/colors/index.ts
yarn.lock

- Storybook に Tailwind を導入した
- `tailwind-config` から提供されている色のドキュメントを実装した
Storybook

Docs for colors in tailwind-config

---

packages/react/src/components/TextField/index.story.tsx
packages/react/src/components/TextField/index.tsx

TextFieldのprefix/suffixをReactNodeに対応

---

packages/react/src/components/TextField/index.tsx

複数行テキストフィールドのフォント色を修正

---

packages/react/src/components/LoadingSpinner/index.story.tsx
packages/react/src/components/LoadingSpinner/index.tsx
packages/react/src/index.ts

fix: change Loading to LoadingSpinner

---

packages/react/src/components/Checkbox/index.story.tsx
packages/react/src/components/Checkbox/index.tsx
packages/react/src/index.ts

- Selection Control の Checkbox component を実装
- storybook

Selection Control の Checkbox component を実装

---

misc/icons-cli-denylist

Gift.svgが最適化で壊れるため最適化を行わないように修正

Gift.svgが最適化で壊れるため最適化を行わないように修正

---

packages/react/src/components/MultiSelect/context.ts
packages/react/src/components/MultiSelect/index.story.tsx
packages/react/src/components/MultiSelect/index.test.tsx
packages/react/src/components/MultiSelect/index.tsx
packages/react/src/index.ts

SelectをMultiSelectに変更
⚠️ 破壊的な変更を含みます

SelectをMultiSelectに変更

---

jest.config.mjs
misc/fileTransformer.js

- iconsのdynamic import化で不要になったjestの設定が残っていたので削除した。
```sh
yarn test
yarn build
yarn test:strict
```

不要になったJestの設定を削除

---

.eslintignore
.prettierignore

- /packages/icons/src/icons.ts はもうないので、prettierignore から外す
CI で prettier の警告が出なければ OK

chore: /packages/icons/src/icons.ts no longer exists

---

packages/react/package.json
packages/react/src/components/Modal/index.story.tsx
packages/react/src/components/Modal/index.tsx
yarn.lock

update @react-aria/overlays
useModalOverlay api docs: https://react-spectrum.adobe.com/react-aria/useModalOverlay.html#example
storybook

feat: update @react-aria/overlays@^3.12.1

---

packages/icons-cli/src/concurrently.ts

icons-cli のエラーを修正
https://github.com/pixiv/charcoal/actions/runs/4049820088/jobs/6966599673#step:5:21
ローカル

fix: import p-queue

---

yarn.lock

yarn.lockの重複依存を無くす
```
yarn dedupe
```

chore: yarn dedupe

---

packages/react/package.json
packages/react/src/components/DropdownSelector/Divider.tsx
packages/react/src/components/DropdownSelector/ListBoxSection.tsx
packages/react/src/components/DropdownSelector/Listbox.tsx
packages/react/src/components/DropdownSelector/Option.tsx
packages/react/src/components/DropdownSelector/index.story.tsx
yarn.lock

DropdownSelector に見出しラベルを追加

---

docs/src/components/AppHeader.tsx

fix: サイドメニューの開閉動作を修正

---

packages/styled/src/index.story.tsx
packages/styled/src/index.test.tsx
packages/styled/src/storyHelper.ts

- styled の storybook にエラーが出ている箇所があったのでファイルを分けて修正した
- storybook

fix(react): fix styled storybook error

---

docs/src/pages/@charcoal-ui/react/Button/apiData.tsx
docs/src/pages/@charcoal-ui/react/Button/sections.tsx
docs/yarn.lock
packages/react/src/components/Button/index.story.tsx
packages/react/src/components/Button/index.tsx
packages/react/src/components/Modal/index.story.tsx
packages/react/src/components/Modal/index.tsx

- Buttonのpropsの命名をfixedからfullWidthに変更

v3.0.0: feat: fixed -> fullWidth

---

packages/react/src/components/Modal/index.tsx

- feat: #270 
- コードのリファクタリング
- Storybook
- プレビューチャンネルでは確認しずらいですが、ChromeのDevToolsより、DemensionsをResponsiveにして高さを小さくしたときにスクロールできることが確認できます。

feat: modalを開いてもスクロール可能に

---

docs/src/pages/@charcoal-ui/react/LoadingSpinner/index.page.tsx
docs/yarn.lock
packages/react/src/components/LoadingSpinner/index.tsx

fix: fix LoadingSpinner style

---

packages/react/src/index.ts

CheckboxProps, DropdownSelectorPropsをexportに追加
fix: #295

feat: 型のexportを追加

---

docs/src/components/NavList.tsx
docs/src/pages/@charcoal-ui/tailwind-diff/check.page.tsx
docs/src/pages/@charcoal-ui/tailwind-diff/dump.page.tsx
docs/src/pages/@charcoal-ui/tailwind-diff/quickstart.page.tsx

`@charcoal-ui/tailwind-diff` のドキュメントを追加。元がなかったので一から書く

tailwind-diff のドキュメントを追加

---

packages/react/src/components/SegmentedControl/index.tsx

- SegmentedControlのaria-labelの警告を修正
- childrenをuseRadioに渡すように変更

fix: aria-label warning

---

packages/react/src/components/Button/__snapshots__/index.test.tsx.snap
packages/react/src/components/Button/index.test.tsx

test: buttonのスナップショットを追加

---

docs/src/pages/@charcoal-ui/react/_components/ApiTable.tsx

- requiredカラムをundefeindにしたときに???になってしまう問題を修正

fix: requiredカラムの???を修正

---

docs/src/components/Table.tsx
docs/yarn.lock

- ドキュメントのテーブルで???になるのを修正
- 必須かつデフォルトがない場合を空白で示すことができないためundefiendの時は空白にする

ドキュメントのテーブルで???になるのを修正

---

packages/react/src/components/DropdownSelector/DropdownMenuItem.tsx
packages/react/src/components/DropdownSelector/ListItem/index.story.tsx
packages/react/src/components/DropdownSelector/ListItem/index.tsx
packages/react/src/components/DropdownSelector/MenuItem/index.tsx
packages/react/src/components/DropdownSelector/MenuItem/internals/useMenuItemHandleKeyDown.tsx
packages/react/src/components/DropdownSelector/MenuItemGroup/index.tsx
packages/react/src/components/DropdownSelector/MenuList/index.story.tsx
packages/react/src/components/DropdownSelector/MenuList/index.tsx
packages/react/src/components/DropdownSelector/MenuList/internals/getValuesRecursive.tsx
packages/react/src/components/DropdownSelector/Popover/index.story.tsx
packages/react/src/components/DropdownSelector/Popover/index.tsx
packages/react/src/components/DropdownSelector/utils/findPreviewRecursive.tsx
packages/react/src/components/TextArea/TextArea.story.tsx
packages/react/src/components/TextArea/index.tsx

- https://github.com/pixiv/charcoal/pull/334 こちらをv3.0.0の最新に対応

refactor: reactのimportを削除

---

docs/src/pages/v3.0.0-guide.page.tsx

docs: ariaLabel->labelの変更を追記

---

README.md

- READMEのdocumentへのリンクを最新のものに修正した

fix: update doc url for v3.0.0

---

.github/workflows/publish.yml

- リリースを行うGitHub Actionsを追加しました
- GitHub Actions

yarn release from-package をするActions追加

---

.github/workflows/publish.yml

- `yarn lerna version` のところで y/n 聞かれて止まったので `--yes` を追加

fix: add yes option to yarn lerna version

---

.github/workflows/publish.yml

- YARN_ENABLE_IMMUTABLE_INSTALLSも必要だった

fix: needs YARN_ENABLE_IMMUTABLE_INSTALLS

---

.github/workflows/publish.yml

- `misc/postpublish.sh` にやりたいこと大体すべてが書かれてたのでこれに寄せる

fix: remove deplicate misc/postpublish.sh process

---

.github/workflows/publish.yml
lerna.json
misc/postpublish.sh
package.json
packages/foundation/package.json
packages/icon-files/package.json
packages/icons-cli/package.json
packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/tailwind-diff/package.json
packages/theme/package.json
packages/utils/package.json
yarn.lock

- npmjsのaccess tokenを渡す箇所が適切でなかったのを修正
- registryのURL指定が無かったのを修正
- npmjsのパッケージプロべナンスに対応
- 対応のためにlernaをv6.6.2以上にアップデート
- postpublish処理変更
- default branch 以外でもpublishできるように変更
動いているActions  
publishされているバージョン（3.1.2-beta.n）
https://www.npmjs.com/search?q=%40charcoal-ui

publishのworkflowを修正

---

packages/react/src/components/Checkbox/__snapshots__/snapshot.test.tsx.snap
packages/react/src/components/Checkbox/snapshot.test.tsx

- checkbox の snapshot test を追加
- 自前環境の `yarn test`

chore(react): add checkbox snapshot test

---

docs/yarn.lock
packages/react/src/core/CharcoalProvider.tsx

fix: add background to CharcoalProvider

---

docs/yarn.lock
packages/react/src/_lib/useForwardedRef.tsx
packages/react/src/components/Modal/Dialog/index.tsx
packages/react/src/components/Modal/index.story.tsx
packages/react/src/components/Modal/index.tsx

- 自動的にmodal内にフォーカスが移動しない問題を修正
- useDialogが適切に利用されるように修正
- 不必要なDOMを1つになるように変更
- ボトムシートの最大幅が固定される問題を修正

fix: 自動的にmodal内にフォーカスが移動しない問題を修正 + etc

---

packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
packages/react/src/components/TextField/index.tsx

- 実際のinput領域が幅いっぱいではなく若干短い
- invalidを指定したときに常にbox-shadowが表示されなくなっている
- disabledにした場合にもhoverで色が変わっている

fix: textFieldのスタイルを修正

---

packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
packages/react/src/components/TextArea/index.tsx
packages/react/src/components/TextField/index.tsx
packages/react/src/components/TextField/useFocusWithClick.tsx

- TextAreaのスタイルを修正
- スクロールバーを表示できるように修正
- 余白をクリックした際もフォーカスするように修正
- theme()記法を削除

feat: textAreaのスタイルを修正

---

.storybook/theme-decorator.tsx

- TokenInjectorのbackgroundを設定した
- storybook

表示するthemeに応じて背景色を変える

---

packages/react/src/components/LoadingSpinner/__snapshots__/index.story.storyshot
packages/react/src/components/LoadingSpinner/index.tsx

- LoadingSpinner から charcoal/styled を抜いた
- storybook

remove styled from LoadingSpinner

---

docs/next.config.js
docs/package.json
docs/yarn.lock

- Add bundle-analyzer to the docs.
- To enable the verification of bundle results in an environment closer to the actual production environment.

docs: add bundle-analyzer

---

docs/src/components/NavList.tsx
docs/src/components/tailwind-config/spacing/Spacing.tsx
docs/src/pages/@charcoal-ui/tailwind-config/spacing.page.tsx

- tailwind-configのspacingが見れるdocs追加

tailwind-configのspacing docs追加

---

docs/src/components/NavList.tsx
docs/src/components/tailwind-config/screens/Screens.tsx
docs/src/pages/@charcoal-ui/tailwind-config/screens.page.tsx

- tailwind-configのscreensが見れるdocs追加

tailwind-configのbreak points (screen) docs追加

---

docs/src/components/NavList.tsx
docs/src/components/tailwind-config/colors/Colors.tsx
docs/src/components/tailwind-config/colors/Gradients.tsx
docs/src/components/tailwind-config/colors/TextColors.tsx
docs/src/components/tailwind-config/colors/gradients/utils.ts
docs/src/pages/@charcoal-ui/tailwind-config/colors.page.tsx

- tailwind-configのcolorsを見れるdocs追加

tailwind-configにcolors docs追加

---

packages/react/src/components/Clickable/index.story.tsx

- clickableのstoryをCSF3にした
storybook

/reactのStorybook CSF3化 clickable編

---

packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot

- A hover style has been added to the DropdownSelector.

feat: add a hover style to DropdownSelector

---

packages/react/src/components/Switch/__snapshots__/index.story.storyshot
packages/react/src/components/Switch/index.story.tsx

- Update the story file for the Switch component.
- Rename the default story to "Basic".
- Add below stories.
- Checked
- Labelled
- Disabled
- All stories are now playable.
- Enabled a centered layout.

test:  Update the story for the Switch component.

---

packages/react/src/components/Radio/__snapshots__/index.story.storyshot
packages/react/src/components/Radio/index.story.tsx

- Added the following stories:
- Basic
- Disabled
- Partial Disabled
- Readonly
- Invalid
- All stories are now playable.
- Enabled a centered layout for the stories.
Storybook

test: Updated the stories for the Radio component.

---

packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
packages/react/src/components/TagItem/index.story.tsx

- TagItem story replace to csf3

TagItem story replace to csf3

---

packages/react/src/components/TextField/TextField.story.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot

- TextField story replace to csf3

TextField story replace to csf3

---

packages/react/src/components/SegmentedControl/index.story.tsx

- Replace to csf3 SegmentedControl story

Replace to csf3 SegmentedControl story

---

packages/react/src/components/DropdownSelector/ListItem/index.story.tsx
packages/react/src/components/DropdownSelector/MenuList/index.story.tsx
packages/react/src/components/DropdownSelector/Popover/index.story.tsx
packages/react/src/components/DropdownSelector/index.story.tsx

- DropdownSelectorのstoryをCSF3にした

/reactのStorybook CSF3化 DropdownSelector編

---

packages/react/src/components/Icon/index.story.tsx
packages/react/src/components/IconButton/index.story.tsx

- replace stories for Icon, IconButton with CSF3.

replace Icon story to CSF3

---

packages/react/src/components/TextArea/TextArea.story.tsx
packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot

TextArea replace to csf3

---

packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
packages/react/src/components/IconButton/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot

- Updated the IconButton to change colors on hover and active states, similar to the Button component.

feat: added color to IconButton's hover and active selectors

---

packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/index.story.tsx
packages/react/src/components/Modal/useCustomModalOverlay.tsx

- Added the usePreventScroll feature to the modal. It had been removed in this [change](https://github.com/pixiv/charcoal/pull/472/files#diff-ca131c1db8dbbbbba217403ae11c176e6899ed9f9451c6d37776448895526dc6R15).
ref. https://github.com/adobe/react-spectrum/blob/d66cf4d8cd4657c562ce52d3f37df0a1fa685416/packages/%40react-aria/overlays/src/useModalOverlay.ts#L53

Fix: Modal does not prevent body scrolling.

---

.github/workflows/test.yml
.gitignore
.storybook/test-runner.ts
package.json
yarn.lock

- add `.storybook/test-runner.ts` image snapshot configurations

Configured test-runner for image snapshot testing

---

packages/react/src/components/DropdownSelector/MenuItem/internals/useMenuItemHandleKeyDown.tsx
packages/react/src/components/DropdownSelector/MenuList/MenuListContext.ts
packages/react/src/components/DropdownSelector/MenuList/index.tsx
packages/react/src/components/DropdownSelector/MenuList/internals/getValuesRecursive.tsx
packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.story.tsx

- Fixed #479
- Updated the story for testing purposes.
- Modified MenuListContext so it can accept DropdownMenuItemProps[] to check for disabled items.
Storybook

Fix: disabled items can be selected using the keyboard.

---

packages/styled/src/__snapshots__/index.story.storyshot
packages/styled/src/index.story.tsx

- Changed the story title to `styled/example`.
- Since the packages are different, we should split the scope.

Test: Changed the story title of the `styled/example`.

---

docs/src/pages/@charcoal-ui/react/DropdownSelector/apiData.tsx
docs/yarn.lock
packages/react/src/components/DropdownSelector/MenuItem/internals/useMenuItemHandleKeyDown.tsx
packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.story.tsx
packages/react/src/components/DropdownSelector/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot

- Added hidden `<select />` element to the `DropdownSelector`.
- This allows it to function correctly within a form element.
- The name property can add a name attribute to the `<select />` element.

Feat: Added hidden `<select />` to the `DropdownSelector`.

---

.storybook/test-runner.ts

- Change image snapshot test threshold. 0.001 -> 0.0001
- Add 200ms delay

Change image snapshot test threshold, add waiting 200ms

---

.storybook/test-runner.ts
packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.tsx

- Fixed #447 .
- Changed the placeholder text color `text2` to `text3`.

Fix: the `placeholder` of the `DropdownSelector` should be `text3`.

---

packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/ListItem/index.tsx
packages/react/src/components/DropdownSelector/MenuList/__snapshots__/index.story.storyshot

- Modified DropdownMenuItem styles.
- Removed hover style on the disabled items.
- Added the transition background.

Fix: Modified DropdownMenuItem styles.

---

docs/package.json
docs/yarn.lock
packages/foundation/package.json
packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/theme/package.json

- Add types field to exports of pakcage.json

Add types field to exports of pakcage.json

---

.github/workflows/publish.yml
lerna.json
package.json
packages/esbuild-plugin-styled-components/package.json
packages/foundation/package.json
packages/icon-files/package.json
packages/icons-cli/package.json
packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/tailwind-diff/package.json
packages/theme/package.json
packages/utils/package.json
yarn.lock

- Add release scripts dist-tag option

Add release scripts dist-tag option

---

packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot

- Fixed #490 .
- Added the `onChange` attribute to the hidden `<select />` element to avoid error logs.
```bash
yarn storybook
```
http://localhost:6006/?path=/story/dropdownselector--default

Fixed: Got an error log when using DropdownSelector.

---

packages/react/src/components/Button/__snapshots__/index.story.storyshot
packages/react/src/components/Button/index.story.tsx
packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot

Merge `v3.10.1` into `v4.0.0`

---

package.json
packages/icons/src/PixivIcon.story.tsx
yarn.lock

- replace to csf3 PixivIcon story
- added storybook/web-components to create a storybook for WebComponents

replace to csf3 PixivIcon story

---

docs/src/pages/@charcoal-ui/react/Button/apiData.tsx
docs/yarn.lock
packages/react/src/components/Button/__snapshots__/index.test.tsx.snap
packages/react/src/components/Button/index.test.tsx
packages/react/src/components/Button/index.tsx

- Added `componentAs` to the `Button`.
- Omitted the as property from the props of T to avoid conflicts with the as property.

Feat: Added `componentAs` to the `Button`.

---

packages/react/src/components/Modal/useCustomModalOverlay.tsx

- Replaced usePreventScroll with a custom implementation.
- The [preventScrollMobileSafari](https://github.com/adobe/react-spectrum/blob/1697a7fef3516f7a194f43b75edb858589ef6535/packages/%40react-aria/overlays/src/usePreventScroll.ts#L107) may have caused focus issues in the Modal.
https://github.com/pixiv/charcoal/assets/35446607/80f6579e-3990-479a-8ac3-6e854ad77434
https://github.com/pixiv/charcoal/assets/35446607/f734aeb4-cea8-4a01-b9f8-708aaabe1849
https://github.com/pixiv/charcoal/assets/35446607/f6c882c2-378c-4e35-a406-5d6949ad9bb1
https://github.com/pixiv/charcoal/assets/35446607/e26e1564-5f56-499d-840b-ed2235f29300

Fix: input handling for software keyboard in modal dialogs

---

packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
packages/react/src/components/IconButton/index.story.tsx

- IconButton の story を整理
- snapshot を update

chore: IconButton story

---

packages/react/src/components/Radio/__snapshots__/index.story.storyshot
packages/react/src/components/Radio/index.story.tsx

- Radio の story を整理
- snapshot を更新

chore: Radio story

---

packages/react/src/components/Switch/__snapshots__/index.story.storyshot
packages/react/src/components/Switch/index.story.tsx

- switch story の整理
- スナップショットの更新

chore: switch story

---

packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
packages/react/src/components/TagItem/index.story.tsx

- TagItem Story の整理
- snapshot の更新

chore: TagItem Story

---

.husky/commit-msg
.prettierignore
package.json
yarn.lock

- hysky の update
- hysky の commit-msg hook が動くように
- vscode の git GUI
- commitlint が動くことは確認したが lint-staged とか入っていた気がするけど気のせいだったか？

chore: update-husky

---

packages/react-sandbox/.npmignore
packages/react-sandbox/tsconfig.build.json
packages/react/.npmignore
packages/react/tsconfig.build.json
packages/styled/.npmignore
packages/tailwind-config/.npmignore

- follow up of https://github.com/pixiv/charcoal/pull/511

fix: add npmignore for snapshots

---

packages/react/src/components/MultiSelect/__snapshots__/index.story.storyshot
packages/react/src/components/MultiSelect/index.story.tsx

- refactor react/MultiSelect stories

replac MultiSelect stories to CSF3

---

.storybook/main.js

- `sideEffects: true` を style-loader の options に追加
- storybook

add sideEffects: true to style-loader

---

packages/react/src/components/Checkbox/__snapshots__/index.story.storyshot
packages/react/src/components/Checkbox/index.story.tsx
packages/react/src/components/Checkbox/index.tsx

- Update the styles of the readonly Checkbox.
- Update the Checkbox story.

Update the styles of the readonly Checkbox

---

.storybook/main.js
.storybook/preview.js
.storybook/src/README.mdx
packages/styled/src/README.mdx
packages/styled/src/__snapshots__/addThemeUtils.story.storyshot
packages/styled/src/addThemeUtils.mdx
packages/styled/src/addThemeUtils.story.tsx
packages/styled/src/createTheme.mdx
packages/styled/src/index.test.tsx

- Add README.mdx
- Add `@charcoal-ui/styled` docs

Feat: add docs for storybook

---

.github/workflows/test-storybook.yml

- アーティファクト生成時のブランチを PR のベースブランチにする
- CI

chore: test-storybook prepare base branch diff

---

packages/tailwind-config/src/docs/borderRadius/index.mdx
packages/tailwind-config/src/docs/colors/index.mdx
packages/tailwind-config/src/docs/gradient/index.mdx
packages/tailwind-config/src/docs/screens/index.mdx
packages/tailwind-config/src/docs/spacing/index.mdx
packages/tailwind-config/src/docs/typography/index.mdx

- tailwind の style が storybook の style で上書きされていたのを修正
- storybook

chore(tailwind-config): wrap unstyled component

---

packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/DropdownSelector/index.tsx
packages/react/src/components/FieldLabel/index.css
packages/react/src/components/FieldLabel/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
packages/react/src/components/TextArea/index.tsx
packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
packages/react/src/components/TextField/index.tsx

- Change `styled-components` to css
- Adjust `TextField`, `TextArea` and `DropdownSelector` styles.

feat: update FieldLabel v4

---

packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/Dialog/index.css
packages/react/src/components/Modal/Dialog/index.tsx
packages/react/src/components/Modal/ModalPlumbing.css
packages/react/src/components/Modal/ModalPlumbing.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/index.css
packages/react/src/components/Modal/index.tsx

- Change `styled-components` to css

feat: update Modal v4

---

packages/theme/src/docs/Color.mdx
packages/theme/src/docs/README.mdx
packages/theme/src/docs/ThemeColors.tsx

- migrate docs to storybook
- storybook

chore(theme): migrate docs

---

packages/icons/src/CustomIcon.mdx
packages/icons/src/README.mdx
packages/icons/src/SSR.mdx

- migrate docs to storybook
- storybook

feat(icons):  convert readme icons

---

packages/styled/src/README.mdx

- Migrate guide from docs to storybook.
- storybook

chore(styled): update storybook guide

---

packages/tailwind-config/src/Custom.mdx
packages/tailwind-config/src/README.mdx

- Migrate guide from docs to storybook.
- storybook

chore(tailwind-config): update storybook guide

---

packages/tailwind-diff/src/Check.mdx
packages/tailwind-diff/src/Dump.mdx
packages/tailwind-diff/src/REAMDE.mdx

- migrate docs to storybook
- storybook

chore(tailwind-diff): migrate docs

---

packages/foundation/src/README.mdx

- migrate docs to storybook
- storybook

chore(foundation): migrate docs

---

.storybook/preview.js
packages/icons/src/CustomIcon.mdx
packages/tailwind-config/src/README.mdx

- reorder story docs
- rename story name
- storybook
[![Image from Gyazo](https://i.gyazo.com/e1d0c1db3b610a5aaac37ef2889ed358.png)](https://gyazo.com/e1d0c1db3b610a5aaac37ef2889ed358)

chore: reorder docs story

---

.github/workflows/test-storybook.yml

- fix VRT CI 
- github actions

fix VRT CI 

---

packages/react/src/components/Modal/Dialog/index.tsx
packages/react/src/components/Modal/__snapshots__/index.story.storyshot
packages/react/src/components/Modal/index.story.tsx

- Fix: modal size is not working.
- Fix: story styles.

fix: modal size is not working

---

packages/pullrequest-cli/package.json

- Changed pullrequest-cli to a private package.

Changed pullrequest-cli to a private package.

---

packages/token-cli/package.json

- `token-cli` package.json changed
- add version
- copy from another package.json version
- add files
- add license
- add type

chore(token-cli): change package.json

---

packages/pullrequest-cli/package.json

chore(pullrequest-cli): remove publishConfig

---

packages/react/src/components/IconButton/index.tsx

- IconButton
- replace as to component

feat: replace as to component IconButton.

---

packages/token-cli/pixiv-dark.config.js
packages/token-cli/pixiv-light.config.js

chore(token-cli): change selector v4.0.0

---

packages/token-cli/pixiv-dark.config.js
packages/token-cli/pixiv-light.config.js

chore(token-cli): change selector

---

.github/workflows/tokens.yml

feat(token-cli): add new category token for v4

---

packages/styled/src/index.ts
packages/styled/src/utils/typographyCss.ts

feat: export removeHalfLeadingCss for migration

---

.github/workflows/tokens.yml

- border-width, paragraph-width, textのカテゴリのtokenを出力するようにしました

feat(token-cli): add new category token

---

packages/theme/cli/token-object.ts

- fix(@charcoal-ui/theme)!: unify css variables json

fix: unify css variables json

---

.github/workflows/bundle-size.yml
.github/workflows/docs-hosting-pr.yml
.github/workflows/test-storybook.yml
.github/workflows/test.yml

- CI 設定の修正 reverts https://github.com/pixiv/charcoal/pull/276

fix: update ci config

---

.github/workflows/tokens.yml
packages/pullrequest-cli/src/getChangedFiles.ts

fix: keep dts and fix copy target path when update theme

---

packages/token-cli/src/figma/index.ts

- https://github.com/pixiv/charcoal/pull/657#issuecomment-2541339239

fix: resolveFloat font weight

---

packages/react/docs/TokenV2Demo.bench.tsx

- feat: add token v2 demo bench

feat: add token v2 demo bench

---

packages/react/docs/TokenV2DemoTailwind.tsx
packages/react/docs/__snapshots__/TokenV2Demo.story.storyshot

- fix: tailwind demo space classnames

fix: tailwind token v2 demo classnames

---

packages/react-sandbox/src/components/HintText/index.story.tsx
packages/react-sandbox/src/components/HintText/index.tsx

- https://github.com/pixiv/charcoal/pull/679 backport

v3 backport: abcang/hint-text-overflow-wrap-break-word

---

.github/workflows/bundle-size.yml
.github/workflows/docs-hosting-pr.yml
.github/workflows/test.yml

- v3 branchでもtestなどのCIを回すようにします

v3ブランチで実行するciを増やす

---

packages/react-sandbox/tsup.config.ts
packages/react/tsup.config.ts

- **fix: add use client banner for rsc**
- https://react.dev/reference/rsc/use-client

fix: add use client banner for rsc

---

packages/react/src/components/TextArea/index.css

- **fix: aria-disabled selector is invaild can cause compiler error**

fix: invalid css :not selector

---

charcoal.code-workspace

- vscode workspace json が欲しかったので作りました

chore: add vscode workspace settings

---

packages/icons/package.json
packages/react-sandbox/package.json
packages/react/package.json
packages/styled/package.json
packages/tailwind-config/package.json
packages/theme/package.json
packages/utils/package.json
pnpm-lock.yaml

build: パッケージ間依存関係をworkspace:*に変更

---

misc/fix-versioning.mjs
misc/postpublish.sh

chore: fix postscript

---

.github/workflows/icons.yml
pnpm-lock.yaml

fix: icon deny list

---

.github/workflows/test-storybook.yml
.storybook/test-runner.ts
package.json

- storybook の build をしてなかったのが原因だったので build するように修正
- snapshot の閾値を少し高くした

fix: VRT が失敗するのを修正

---

packages/react-sandbox/src/components/HintText/index.tsx
packages/react/src/components/HintText/__snapshots__/index.story.storyshot
packages/react/src/components/HintText/index.css
packages/react/src/components/HintText/index.story.tsx
packages/react/src/components/HintText/index.tsx

- implement HintText in react package

feat: impl HintText in react package

---

.gitignore
packages/icons/.npmignore
packages/icons/package.json
packages/icons/tsconfig.build.json
packages/icons/tsconfig.react.json

fix: icons v2 publish

---

packages/icon-files/package.json

chore: add missing v1-datauri to files in package.json in order to publish it to NPM

---

packages/icons-cli/src/v2/transformCSS.ts
packages/icons/css/v1/index.css
packages/icons/css/v1/index.html
packages/icons/css/v1/index.story.tsx

- update css v1 icons and update markup

fix: css v1 markup
